name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Please describe the bug as concrete as possible
      placeholder:
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior (e.g. which publishers did you crawl? which parameters did you use?).
      placeholder: |
        from fundus import Crawler, PublisherCollection
        crawler = Crawler(...)
        ...
      render: python
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Context information about the setup you're using
      placeholder: |
        Fundus branch/version: e.g. master
        Python version: e.g 3.8.x
  - type: textarea
    id: error
    attributes:
      label: Logs and Stack traces
      description: If applicable, please past any relevant logs or error messages, please don't cut off the stack trace.
      placeholder: |
        Traceback (most recent call last):
        File "C:/Users/maxda/PycharmProjects/fundus/scratch.py", line 321, in <module>
        source = HTMLSource()
        TypeError: __init__() missing 2 required positional arguments: ...
      render: stacktrace
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: if applicable, copy paste an image in here
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add anything worthy to add that wasn't mentioned yet.
    validations:
      required: false