name: tests

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_call:

jobs:
  pytest:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        id: setup
        with:
          python-version: 3.8
          cache: pip

      - name: Install dependencies
        if: steps.setup.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run pytest
        run: python -m pytest -vv

  mypy:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        id: setup
        with:
          python-version: 3.8
          cache: pip

      - name: Install dependencies
        if: steps.setup.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run mypy
        run: python -m mypy .
